import type { Product, Court, Tournament, Coach, Post } from '../types';

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    vendorId: 'vendor-1',
    vendor: {
      id: 'vendor-1',
      name: 'Juan Deportes',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vendor',
      rating: 4.8,
    },
    name: 'Balón de Fútbol Profesional',
    description: 'Balón de fútbol profesional, tamaño 5, certificado FIFA. Ideal para partidos y entrenamientos de alto rendimiento.',
    price: 120000,
    images: [
      'https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?w=800',
      'https://images.unsplash.com/photo-1575361204480-aadea25e6e68?w=800',
    ],
    category: 'Fútbol',
    subcategory: 'Balones',
    stock: 45,
    rating: 4.7,
    reviewCount: 128,
    featured: true,
    tags: ['fútbol', 'profesional', 'FIFA'],
    createdAt: '2026-04-15T10:00:00Z',
    updatedAt: '2026-05-10T15:30:00Z',
  },
  {
    id: 'prod-2',
    vendorId: 'vendor-1',
    vendor: {
      id: 'vendor-1',
      name: 'Juan Deportes',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vendor',
      rating: 4.8,
    },
    name: 'Zapatillas Nike Mercurial',
    description: 'Zapatillas de fútbol Nike Mercurial con tecnología de última generación para máximo rendimiento en el campo.',
    price: 450000,
    images: [
      'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
    ],
    category: 'Fútbol',
    subcategory: 'Calzado',
    stock: 28,
    rating: 4.9,
    reviewCount: 95,
    featured: true,
    tags: ['fútbol', 'Nike', 'profesional', 'calzado'],
    createdAt: '2026-04-10T10:00:00Z',
    updatedAt: '2026-05-09T15:30:00Z',
  },
  {
    id: 'prod-3',
    vendorId: 'vendor-1',
    vendor: {
      id: 'vendor-1',
      name: 'Juan Deportes',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vendor',
      rating: 4.8,
    },
    name: 'Raqueta de Tenis Wilson Pro',
    description: 'Raqueta de tenis profesional Wilson con balance perfecto y máximo control. Ideal para jugadores intermedios y avanzados.',
    price: 380000,
    images: [
      'https://images.unsplash.com/photo-1617883861744-2d87203e4bb8?w=800',
      'https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800',
    ],
    category: 'Tenis',
    subcategory: 'Raquetas',
    stock: 15,
    rating: 4.6,
    reviewCount: 52,
    featured: false,
    tags: ['tenis', 'Wilson', 'profesional'],
    createdAt: '2026-04-20T10:00:00Z',
    updatedAt: '2026-05-08T15:30:00Z',
  },
  {
    id: 'prod-4',
    vendorId: 'vendor-1',
    vendor: {
      id: 'vendor-1',
      name: 'Juan Deportes',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vendor',
      rating: 4.8,
    },
    name: 'Set de Pesas Ajustables 20kg',
    description: 'Set completo de pesas ajustables de 5kg a 20kg por mancuerna. Perfecto para entrenamientos en casa o gimnasio.',
    price: 280000,
    images: [
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800',
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800',
    ],
    category: 'Gimnasio',
    subcategory: 'Pesas',
    stock: 32,
    rating: 4.8,
    reviewCount: 167,
    featured: true,
    tags: ['gimnasio', 'pesas', 'entrenamiento'],
    createdAt: '2026-03-25T10:00:00Z',
    updatedAt: '2026-05-11T15:30:00Z',
  },
  {
    id: 'prod-5',
    vendorId: 'vendor-1',
    vendor: {
      id: 'vendor-1',
      name: 'Juan Deportes',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vendor',
      rating: 4.8,
    },
    name: 'Bicicleta de Montaña Trek',
    description: 'Bicicleta de montaña Trek con suspensión completa, 21 velocidades y frenos de disco. Lista para cualquier terreno.',
    price: 2500000,
    images: [
      'https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=800',
      'https://images.unsplash.com/photo-1571333250630-f0230c320b6d?w=800',
    ],
    category: 'Ciclismo',
    subcategory: 'Bicicletas',
    stock: 8,
    rating: 4.9,
    reviewCount: 43,
    featured: true,
    tags: ['ciclismo', 'montaña', 'Trek'],
    createdAt: '2026-04-05T10:00:00Z',
    updatedAt: '2026-05-07T15:30:00Z',
  },
  {
    id: 'prod-6',
    vendorId: 'vendor-1',
    vendor: {
      id: 'vendor-1',
      name: 'Juan Deportes',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vendor',
      rating: 4.8,
    },
    name: 'Balón de Baloncesto Spalding',
    description: 'Balón oficial de baloncesto Spalding, tamaño 7. Excelente agarre y rebote para juego indoor y outdoor.',
    price: 95000,
    images: [
      'https://images.unsplash.com/photo-1546483875-ad9014c88eba?w=800',
      'https://images.unsplash.com/photo-1519861531473-9200262188bf?w=800',
    ],
    category: 'Baloncesto',
    subcategory: 'Balones',
    stock: 52,
    rating: 4.7,
    reviewCount: 89,
    featured: false,
    tags: ['baloncesto', 'Spalding', 'NBA'],
    createdAt: '2026-04-18T10:00:00Z',
    updatedAt: '2026-05-06T15:30:00Z',
  },
];

export const mockCourts: Court[] = [
  {
    id: 'court-1',
    ownerId: 'court-1',
    owner: {
      id: 'court-1',
      name: 'Deportivo Tolima',
      phone: '+57 300 123 4567',
    },
    name: 'Cancha de Fútbol Sintética El Jordán',
    description: 'Cancha de fútbol 11 con césped sintético de última generación, iluminación LED y gradas para 100 personas.',
    images: [
      'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=800',
      'https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800',
    ],
    sport: 'Fútbol',
    location: {
      address: 'Calle 42 #15-23',
      city: 'Ibagué, Tolima',
      coordinates: {
        lat: 4.4389,
        lng: -75.2322,
      },
    },
    amenities: ['Vestuarios', 'Duchas', 'Iluminación', 'Parqueadero', 'Cafetería'],
    pricePerHour: 80000,
    availability: [
      { dayOfWeek: 1, startTime: '06:00', endTime: '22:00' },
      { dayOfWeek: 2, startTime: '06:00', endTime: '22:00' },
      { dayOfWeek: 3, startTime: '06:00', endTime: '22:00' },
      { dayOfWeek: 4, startTime: '06:00', endTime: '22:00' },
      { dayOfWeek: 5, startTime: '06:00', endTime: '22:00' },
      { dayOfWeek: 6, startTime: '07:00', endTime: '23:00' },
      { dayOfWeek: 0, startTime: '07:00', endTime: '23:00' },
    ],
    rating: 4.8,
    reviewCount: 142,
    featured: true,
    createdAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'court-2',
    ownerId: 'court-1',
    owner: {
      id: 'court-1',
      name: 'Deportivo Tolima',
      phone: '+57 300 123 4567',
    },
    name: 'Canchas de Tenis Club Campestre',
    description: 'Dos canchas de tenis en polvo de ladrillo profesional, con iluminación nocturna y área de descanso.',
    images: [
      'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800',
      'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=800',
    ],
    sport: 'Tenis',
    location: {
      address: 'Carrera 5 #60-45',
      city: 'Ibagué, Tolima',
      coordinates: {
        lat: 4.4489,
        lng: -75.2422,
      },
    },
    amenities: ['Vestuarios', 'Duchas', 'Iluminación', 'Zona de descanso', 'Tienda deportiva'],
    pricePerHour: 45000,
    availability: [
      { dayOfWeek: 1, startTime: '06:00', endTime: '21:00' },
      { dayOfWeek: 2, startTime: '06:00', endTime: '21:00' },
      { dayOfWeek: 3, startTime: '06:00', endTime: '21:00' },
      { dayOfWeek: 4, startTime: '06:00', endTime: '21:00' },
      { dayOfWeek: 5, startTime: '06:00', endTime: '21:00' },
      { dayOfWeek: 6, startTime: '07:00', endTime: '20:00' },
      { dayOfWeek: 0, startTime: '07:00', endTime: '20:00' },
    ],
    rating: 4.9,
    reviewCount: 87,
    featured: true,
    createdAt: '2026-02-15T10:00:00Z',
  },
  {
    id: 'court-3',
    ownerId: 'court-1',
    owner: {
      id: 'court-1',
      name: 'Deportivo Tolima',
      phone: '+57 300 123 4567',
    },
    name: 'Cancha de Baloncesto Cubierta',
    description: 'Cancha de baloncesto completamente cubierta con piso en madera profesional y gradas para 200 personas.',
    images: [
      'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800',
      'https://images.unsplash.com/photo-1608245449230-4ac19066d2d0?w=800',
    ],
    sport: 'Baloncesto',
    location: {
      address: 'Carrera 8 #25-10',
      city: 'Ibagué, Tolima',
      coordinates: {
        lat: 4.4289,
        lng: -75.2222,
      },
    },
    amenities: ['Vestuarios', 'Duchas', 'Aire acondicionado', 'Gradas', 'Tableros electrónicos'],
    pricePerHour: 65000,
    availability: [
      { dayOfWeek: 1, startTime: '07:00', endTime: '22:00' },
      { dayOfWeek: 2, startTime: '07:00', endTime: '22:00' },
      { dayOfWeek: 3, startTime: '07:00', endTime: '22:00' },
      { dayOfWeek: 4, startTime: '07:00', endTime: '22:00' },
      { dayOfWeek: 5, startTime: '07:00', endTime: '22:00' },
      { dayOfWeek: 6, startTime: '08:00', endTime: '21:00' },
      { dayOfWeek: 0, startTime: '08:00', endTime: '21:00' },
    ],
    rating: 4.7,
    reviewCount: 65,
    featured: false,
    createdAt: '2026-03-10T10:00:00Z',
  },
];

export const mockTournaments: Tournament[] = [
  {
    id: 'tournament-1',
    organizerId: 'organizer-1',
    organizer: {
      id: 'organizer-1',
      name: 'Carlos Torneos',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=organizer',
    },
    name: 'Copa Tolima Fútbol 2026',
    description: 'Torneo de fútbol 11 masculino, categoría abierta. Formato eliminación directa con 16 equipos participantes.',
    sport: 'Fútbol',
    image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
    startDate: '2026-06-15T00:00:00Z',
    endDate: '2026-07-15T00:00:00Z',
    registrationDeadline: '2026-06-01T00:00:00Z',
    location: 'Estadio Manuel Murillo Toro, Ibagué',
    maxParticipants: 16,
    currentParticipants: 12,
    entryFee: 500000,
    prizes: ['$3.000.000 primer lugar', '$1.500.000 segundo lugar', '$750.000 tercer lugar'],
    rules: 'Reglamento FIFA, equipos de 11 jugadores + 5 suplentes. Dos tiempos de 45 minutos.',
    status: 'upcoming',
    featured: true,
    createdAt: '2026-04-01T10:00:00Z',
  },
  {
    id: 'tournament-2',
    organizerId: 'organizer-1',
    organizer: {
      id: 'organizer-1',
      name: 'Carlos Torneos',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=organizer',
    },
    name: 'Torneo Relámpago de Tenis',
    description: 'Torneo de tenis individual, formato suizo, todas las categorías bienvenidas.',
    sport: 'Tenis',
    image: 'https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67?w=800',
    startDate: '2026-05-25T00:00:00Z',
    endDate: '2026-05-26T00:00:00Z',
    registrationDeadline: '2026-05-20T00:00:00Z',
    location: 'Club Campestre de Ibagué',
    maxParticipants: 32,
    currentParticipants: 24,
    entryFee: 80000,
    prizes: ['Raqueta Wilson Pro', 'Set de pelotas', 'Trofeos para los 3 primeros'],
    rules: 'Sets a 6 juegos, tie-break en 6-6. Final a mejor de 3 sets.',
    status: 'upcoming',
    featured: true,
    createdAt: '2026-04-20T10:00:00Z',
  },
  {
    id: 'tournament-3',
    organizerId: 'organizer-1',
    organizer: {
      id: 'organizer-1',
      name: 'Carlos Torneos',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=organizer',
    },
    name: 'Liga de Baloncesto Universitario',
    description: 'Liga de baloncesto universitario, fase todos contra todos. Solo estudiantes activos.',
    sport: 'Baloncesto',
    image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800',
    startDate: '2026-05-15T00:00:00Z',
    endDate: '2026-08-15T00:00:00Z',
    registrationDeadline: '2026-05-10T00:00:00Z',
    location: 'Coliseo Municipal de Ibagué',
    maxParticipants: 8,
    currentParticipants: 8,
    entryFee: 400000,
    prizes: ['$2.000.000 primer lugar', '$1.000.000 segundo lugar', 'Balones oficiales'],
    rules: 'Reglamento FIBA, 4 cuartos de 10 minutos. Requiere carnet universitario vigente.',
    status: 'ongoing',
    featured: false,
    createdAt: '2026-03-15T10:00:00Z',
  },
];

export const mockCoaches: Coach[] = [
  {
    id: 'coach-1',
    userId: 'coach-1',
    user: {
      id: 'coach-1',
      email: 'coach@tolima.com',
      name: 'Andrés Martínez',
      role: 'coach',
      roles: ['coach'],
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=coach',
      createdAt: new Date().toISOString(),
      location: 'Ibagué, Tolima',
      bio: 'Entrenador certificado con 10 años de experiencia',
    },
    specialties: ['Fútbol', 'Preparación Física', 'Táctica'],
    experience: '10 años como entrenador profesional. Ex-jugador profesional de la liga colombiana.',
    certifications: ['Licencia UEFA B', 'Preparador Físico Certificado', 'Nutrición Deportiva'],
    bio: 'Entrenador apasionado con más de 10 años formando jugadores de élite. Especializado en desarrollo técnico y táctico.',
    hourlyRate: 50000,
    availability: 'Lunes a Viernes: 6am-9am y 5pm-8pm. Sábados: 7am-12pm',
    rating: 4.9,
    reviewCount: 67,
    featured: true,
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'coach-2',
    userId: 'coach-2',
    user: {
      id: 'coach-2',
      email: 'laura@coach.com',
      name: 'Laura Rodríguez',
      role: 'coach',
      roles: ['coach'],
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=laura',
      createdAt: new Date().toISOString(),
      location: 'Ibagué, Tolima',
      bio: 'Entrenadora especializada en tenis',
    },
    specialties: ['Tenis', 'Técnica', 'Mentalidad Deportiva'],
    experience: '8 años entrenando tenistas de todas las edades. Ex-top 100 WTA.',
    certifications: ['Certificación ITF Nivel 2', 'Psicología Deportiva', 'Coaching Mental'],
    bio: 'Ex-tenista profesional dedicada a formar nuevos talentos con enfoque en técnica y mentalidad ganadora.',
    hourlyRate: 60000,
    availability: 'Martes a Domingo: 7am-11am y 4pm-7pm',
    rating: 4.8,
    reviewCount: 52,
    featured: true,
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'coach-3',
    userId: 'coach-3',
    user: {
      id: 'coach-3',
      email: 'jorge@coach.com',
      name: 'Jorge Valencia',
      role: 'coach',
      roles: ['coach'],
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jorge',
      createdAt: new Date().toISOString(),
      location: 'Ibagué, Tolima',
      bio: 'Entrenador de alto rendimiento',
    },
    specialties: ['Gimnasio', 'Musculación', 'Pérdida de Peso', 'Nutrición'],
    experience: '12 años en entrenamiento personalizado y preparación física de atletas.',
    certifications: ['Personal Trainer NSCA', 'Nutrición Deportiva', 'CrossFit Level 2'],
    bio: 'Especialista en transformaciones físicas y preparación atlética de alto rendimiento.',
    hourlyRate: 45000,
    availability: 'Lunes a Sábado: 5am-9am y 5pm-9pm',
    rating: 4.7,
    reviewCount: 89,
    featured: false,
    createdAt: '2026-01-20T10:00:00Z',
  },
];

export const mockPosts: Post[] = [
  {
    id: 'post-1',
    userId: 'customer-1',
    user: {
      id: 'customer-1',
      name: 'María González',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=customer',
      role: 'customer',
    },
    content: 'Increíble partido de fútbol hoy en El Jordán! El nivel de las canchas es espectacular. Totalmente recomendado! ⚽',
    images: ['https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=800'],
    likes: 45,
    comments: 12,
    createdAt: '2026-05-11T14:30:00Z',
    sport: 'Fútbol',
  },
  {
    id: 'post-2',
    userId: 'coach-1',
    user: {
      id: 'coach-1',
      name: 'Andrés Martínez',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=coach',
      role: 'coach',
    },
    content: 'Consejos para mejorar tu control de balón: Practica con ambas piernas, mantén la vista en alto, y usa diferentes partes del pie. La constancia es clave! 💪',
    likes: 128,
    comments: 34,
    createdAt: '2026-05-10T09:15:00Z',
    sport: 'Fútbol',
  },
  {
    id: 'post-3',
    userId: 'organizer-1',
    user: {
      id: 'organizer-1',
      name: 'Carlos Torneos',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=organizer',
      role: 'organizer',
    },
    content: 'Últimos cupos disponibles para la Copa Tolima Fútbol 2026! No te quedes por fuera del torneo más importante del año. Inscripciones abiertas hasta el 1 de junio! 🏆',
    images: ['https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800'],
    likes: 92,
    comments: 28,
    createdAt: '2026-05-09T16:45:00Z',
    sport: 'Fútbol',
  },
];

export const categories = [
  'Fútbol',
  'Baloncesto',
  'Tenis',
  'Ciclismo',
  'Gimnasio',
  'Natación',
  'Voleibol',
  'Running',
];
